---
project:
  name: log4brains-tests-ro
  tz: Europe/Paris
  adrFolder: ./docs/adr

  packages:
    - name: package1
      path: ./packages/package1
      adrFolder: ./packages/package1/adr
    - name: package2
      path: ./packages/package2
      adrFolder: ./packages/package2/adr
