name: Post-release E2E
on:
  # Run after every release to NPM
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  # Run on every Wednesday to check possible regressions caused by dependency updates
  # Like this one: https://github.com/thomvaill/log4brains/issues/27
  schedule:
    - cron: "0 4 * * 3"

jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [15.x, 14.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: install
        run: npm install -g log4brains

      - name: test # TODO: add some assertions :-) For now we just check the exit codes
        run: |
          log4brains init --defaults
          log4brains adr list
