name: Post-release E2E
on:
  workflow_dispatch:

  # Run after every release to NPM
  push:
    tags:
      - v*

  # Run on every Wednesday to check possible regressions caused by dependency updates
  # Like this one: https://github.com/thomvaill/log4brains/issues/27
  schedule:
    - cron: "0 4 * * 3"

jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [15.x, 14.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: install
        run: npm install -g log4brains@$(cat lerna.json | jq -r .version)

      - name: test # TODO: test the preview add some assertions :-) For now we just check the exit codes. Or manage to run e2e-tests/e2e-launcher.js from here
        run: |
          log4brains init --defaults
          log4brains adr list
          log4brains build
