name: Post-release Docker Hub
on:
  workflow_dispatch:

  # Run after every release to NPM
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and release the latest Docker image
        run: make -C docker release version-tag latest-tag
